[package]
name = "kafka-producer"
version = "0.1.0"
authors = ["lucas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.8.0"